"""empty message

Revision ID: 2fa6cf2d33fd
Revises: 
Create Date: 2019-06-18 21:12:05.316153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fa6cf2d33fd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_text'), 'question', ['text'], unique=False)
    op.create_table('answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character', sa.String(length=80), nullable=True),
    sa.Column('text', sa.String(length=80), nullable=True),
    sa.Column('nextqID', sa.Integer(), nullable=True),
    sa.Column('isEnd', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['nextqID'], ['question.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nextqID')
    )
    op.create_index(op.f('ix_answer_character'), 'answer', ['character'], unique=False)
    op.create_index(op.f('ix_answer_text'), 'answer', ['text'], unique=False)
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character', sa.String(length=80), nullable=True),
    sa.Column('firstqID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['firstqID'], ['question.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('firstqID')
    )
    op.create_index(op.f('ix_games_character'), 'games', ['character'], unique=False)
    op.create_table('GameImage',
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('mimetype', sa.String(length=255), nullable=False),
    sa.Column('original', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('width', 'height', 'user_id')
    )
    op.create_table('que_ans',
    sa.Column('QueId', sa.Integer(), nullable=True),
    sa.Column('AnsId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['AnsId'], ['answer.id'], ),
    sa.ForeignKeyConstraint(['QueId'], ['question.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('que_ans')
    op.drop_table('GameImage')
    op.drop_index(op.f('ix_games_character'), table_name='games')
    op.drop_table('games')
    op.drop_index(op.f('ix_answer_text'), table_name='answer')
    op.drop_index(op.f('ix_answer_character'), table_name='answer')
    op.drop_table('answer')
    op.drop_index(op.f('ix_question_text'), table_name='question')
    op.drop_table('question')
    # ### end Alembic commands ###
