"""empty message

Revision ID: 80ebf226e055
Revises: 2fa6cf2d33fd
Create Date: 2019-06-18 23:32:10.453420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80ebf226e055'
down_revision = '2fa6cf2d33fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('GameImage')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('GameImage',
    sa.Column('width', sa.INTEGER(), nullable=False),
    sa.Column('height', sa.INTEGER(), nullable=False),
    sa.Column('mimetype', sa.VARCHAR(length=255), nullable=False),
    sa.Column('original', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.CheckConstraint('original IN (0, 1)'),
    sa.ForeignKeyConstraint(['user_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('width', 'height', 'user_id')
    )
    # ### end Alembic commands ###
